### PR TITLE
update rails from 4.2.0 to 4.2.2

### PR DESCRIPTION
**Pull request by Joe-noh**
4.2.0 is vulnerable.

### CODE REVIEW

**Comment by hiboma** [comment]
:+1:

**Comment by Joe-noh** [comment]
テスト通った！

**Comment by hanazuki** [comment]
web-console 2.0.0 and jquery-rails 4.0.3 are vulnerable too.

**Comment by Joe-noh** [comment]
http://weblog.rubyonrails.org/2015/6/16/Rails-3-2-22-4-1-11-and-4-2-2-have-been-released-and-more/

@hanazuki 
ホントだ！全然railsだけじゃない！！

**Pull request merged**
